---
baseURL: "http://mroach.com/"
languageCode: "en-us"
defaultContentLanguage: "en"
title: "Michael Roach"
theme: "mainroad"

permalinks:
  posts: /:year/:month/:title/

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
      xhtml: true
  highlight:
    style: "friendly"
    lineNos: false

params:
  description: "Software, tech, food."
  dateFormat: "2006-01-02"
  pager: true
  readmore: true
  opengraph: true
  twitter_cards: false
  highlightColor: "rgb(58,110,165)"
  post_meta:
    - date
    - categories
  customCSS:
    - "css/custom.css"
  author:
    name: Michael Roach
    avatar: "images/me-sticker.png"

  logo:
    image: images/me-sticker.png
    title: Michael Roach
    subtitle: |
      Technology. Software. Food. Scuba diving.

  widgets:
    social:
      mastodon: https://mas.to/@mroach
      github: mroach
      linkedin: mfroach
      email: web@c.mroach.com

  sidebar:
    home: right
    list: right
    single: false
    widgets:
      - social
      - categories
      - taglist
